### ISSUE TITLE
Ship doesn't move

### ISSUE THREAD

**Issue by ehmatthes** [carlos1103/alien_invasion#4]
When you click play and press the left or right arrow key, the ship doesn't move. To debug this, we should look at the code that handles events. First look at check_events(), then check_keydown_events(), then ship.update(). The issue is in ship.update().

The variable self.center is just a decimal number that's used to keep track of the ship's position. It's not tied to the ship's rect object at all. To position the ship for drawing, we use this line:

    self.rect.centerx = self.center

This line takes the integer part of self.center and uses it to position the ship's rect, which determines where it will be drawn on the screen. When you update the position of the ship in update(), you want to update the value of self.center, not self.centerx.

**Comment by chawy11** [comment]
I don't even know why I wrote that there! Fixed and works correctly! But now I still got the other error I let the alien hit me but instead of creating a new fleet the game kind of crash with plenty of aliens on the screen bugged and I lose the game

**Comment by ehmatthes** [comment]
It's easy to mix up what `self.center` and `self.rect.centerx` each represent. I'll let you close this issue, and we'll open another issue for the next bug.

I do get notifications for any issue that I open, or that I subscribe to.

**Comment by ehmatthes** [comment]
I would like you to open the next issue. Describe what you expect to see, and what you're actually seeing. Write something about why you think it's happening. Otherwise I'm starting to do all the debugging work.

You can tag me in the issue, by writing @ and then my username: @carlos1103
