### ISSUE TITLE
Ship hit, game crashes

### ISSUE THREAD

**Issue by chawy11** [carlos1103/alien_invasion#5]
After the ship is hit by an alien or one hit the bottom the game should pause and create a new fleet, instead the screen get's swamped of aliens,  ship is not able to move until the game is over.

I believe it's has to be related to ship_hit but for some reason the game doesn't create a new fleet after it's hit. Or maybe it's the loop of the game since the game works fine until the ship is hit.

The code seems to be fine but I can't spot the where is the code failing.

@ehmatthes

**Comment by chawy11** [comment]
Found the issue! It was a parentheses in check_play_button I was so wrong about my deductions since the problem was that in reality the aliens were not being emptied so it made the game "crash"

Game finally 100% finished?

**Comment by ehmatthes** [comment]
That's great! What's next for you?

**Comment by chawy11** [comment]
For sure finishing the other 2 projects of your book! Hopefully I do better with the data visualization since I already have some "experience" with matplotlib. Also when I get more confident add more features to the alien game (music, final boss?).

After that I have an eye in other python books of nostarch!

Thank you so much for your help and making the book! 😄

**Comment by ehmatthes** [comment]
You are very welcome, and nice work so far. The data visualization projects should be easier than this because they're a series of smaller projects. So there's more opportunity to start from scratch and build on what you've been learning.
